//! `skm.lock` lockfile: serde read + deterministic `toml_edit` write, atomic
//! file replacement.

use std::path::Path;

use serde::Deserialize;
use toml_edit::{ArrayOfTables, DocumentMut, Item, Table};

use crate::error::{Result, SkmError};
use crate::source::{self, Source, SourceType};
use crate::sys::fsutil;
use crate::sys::hash::Sha256;

pub const LOCK_VERSION: i64 = 1;

pub fn generated_by() -> String {
    format!("skm {}", env!("CARGO_PKG_VERSION"))
}

/// Decide whether to emit a `generated_by` compatibility note, returning
/// `Some(message)` when a warning is warranted and `None` when the two versions
/// are compatible.
///
/// Rule: identical → no note. Pre-1.0.0 (`0.x`) → any version difference
/// warns (0.x may break at any bump). From 1.0.0 onward → only a **major**
/// difference warns; minor/patch are compatible. **Pre-release / build
/// metadata do not participate** in the comparison. Unparseable versions fall
/// back to a raw-inequality note.
pub fn compat_note(lock_generated_by: &str, current: &str) -> Option<String> {
    if lock_generated_by.is_empty() || lock_generated_by == current {
        return None;
    }
    let note = || format!("lock generated by '{lock_generated_by}' (current: '{current}')");
    match (parse_version(lock_generated_by), parse_version(current)) {
        (Some(a), Some(b)) => {
            if a == b {
                // Cores equal → differ only in pre-release/build metadata: ignore.
                None
            } else if a.0 == 0 || b.0 == 0 {
                // 0.x: any difference warns.
                Some(note())
            } else if a.0 != b.0 {
                // >=1.0: only a major-version difference warns.
                Some(format!("{}; major version differs", note()))
            } else {
                // Same major, different minor/patch → compatible, no note.
                None
            }
        }
        // Unparseable on either side: conservative raw-inequality note.
        _ => Some(note()),
    }
}

/// Parse `(major, minor, patch)` from a `"skm X.Y.Z[-pre][+build]"` string,
/// discarding any pre-release / build metadata. Returns `None` if the
/// numeric core cannot be parsed.
fn parse_version(s: &str) -> Option<(u64, u64, u64)> {
    let token = s.split_whitespace().next_back()?;
    let core = token.split('+').next()?; // drop build metadata
    let core = core.split('-').next()?; // drop pre-release
    let mut it = core.split('.');
    let major = it.next()?.parse().ok()?;
    let minor = it.next().unwrap_or("0").parse().ok()?;
    let patch = it.next().unwrap_or("0").parse().ok()?;
    Some((major, minor, patch))
}

#[derive(Debug, Clone)]
pub struct Lockfile {
    pub version: i64,
    pub generated_by: String,
    pub skills: Vec<LockSkill>,
}

/// Abbreviate a hex string (e.g. git commit SHA) to its first 12 chars.
/// Slices on a UTF-8 char boundary: if the 12-byte mark falls inside a
/// multi-byte character, it backs up to the previous boundary. For valid
/// hex input (all ASCII) this is a no-op.
fn short_hex(s: &str) -> &str {
    let end = s.len().min(12);
    if s.is_char_boundary(end) {
        &s[..end]
    } else {
        // Back up to the nearest char boundary. This is defensive: a valid
        // commit SHA is always ASCII, so this path is only taken on corrupt
        // or hand-edited lockfiles.
        let mut i = end;
        while i > 0 && !s.is_char_boundary(i) {
            i -= 1;
        }
        &s[..i]
    }
}

/// Shared `tar`/`zip` summary line: `<kind> <url> [subdir] (sha256:<short>)`.
fn archive_summary(kind: &str, url: &str, subdir: Option<&str>, archive_sha256: &Sha256) -> String {
    let mut s = format!("{kind} {url}");
    if let Some(sd) = subdir {
        s.push_str(&format!(" [subdir: {sd}]"));
    }
    s.push_str(&format!(" (sha256:{})", archive_sha256.short_hex()));
    s
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockSkill {
    pub name: String,
    pub content_sha256: Sha256,
    pub source: LockSource,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockSource {
    Git {
        repo: String,
        ref_: Option<String>,
        subdir: Option<String>,
        resolved_ref: Option<String>,
        resolved_commit: String,
    },
    Tar {
        url: String,
        subdir: Option<String>,
        archive_sha256: Sha256,
    },
    Zip {
        url: String,
        subdir: Option<String>,
        archive_sha256: Sha256,
    },
    Local {
        path: String,
    },
}

impl LockSource {
    pub fn source_type(&self) -> SourceType {
        match self {
            LockSource::Git { .. } => SourceType::Git,
            LockSource::Tar { .. } => SourceType::Tar,
            LockSource::Zip { .. } => SourceType::Zip,
            LockSource::Local { .. } => SourceType::Local,
        }
    }

    /// One-line, human-facing summary of the *resolved* source — i.e. exactly
    /// what is pinned on disk (short commit / archive digest). Used by
    /// `skm add`/`lock` ("Locked X → …") and `skm status` so a reader never has
    /// to open `skm.lock` to learn which version is installed.
    pub fn summary(&self) -> String {
        match self {
            LockSource::Git {
                repo,
                ref_,
                subdir,
                resolved_ref,
                resolved_commit,
            } => {
                let mut s = format!("git {repo}");
                if let Some(r) = resolved_ref.as_deref().or(ref_.as_deref()) {
                    s.push_str(&format!(" @ {r}"));
                }
                s.push_str(&format!(" ({})", short_hex(resolved_commit)));
                if let Some(sd) = subdir {
                    s.push_str(&format!(" [subdir: {sd}]"));
                }
                s
            }
            LockSource::Tar {
                url,
                subdir,
                archive_sha256,
            } => archive_summary("tar", url, subdir.as_deref(), archive_sha256),
            LockSource::Zip {
                url,
                subdir,
                archive_sha256,
            } => archive_summary("zip", url, subdir.as_deref(), archive_sha256),
            LockSource::Local { path } => format!("local {path}"),
        }
    }

    /// Reconstruct a manifest-equivalent [`Source`] for
    /// materialization. Deploy is lock-driven (content from the lock).
    pub fn to_source(&self) -> Source {
        match self {
            LockSource::Git {
                repo, ref_, subdir, ..
            } => Source::Git {
                repo: repo.clone(),
                ref_: ref_.clone(),
                subdir: subdir.clone(),
            },
            LockSource::Tar { url, subdir, .. } => Source::Tar {
                url: url.clone(),
                subdir: subdir.clone(),
                sha256: None,
            },
            LockSource::Zip { url, subdir, .. } => Source::Zip {
                url: url.clone(),
                subdir: subdir.clone(),
                sha256: None,
            },
            LockSource::Local { path } => Source::Local { path: path.clone() },
        }
    }
}

impl Lockfile {
    pub fn empty() -> Self {
        Lockfile {
            version: LOCK_VERSION,
            generated_by: generated_by(),
            skills: Vec::new(),
        }
    }

    pub fn get(&self, name: &str) -> Option<&LockSkill> {
        self.skills.iter().find(|s| s.name == name)
    }

    /// Sort skills ascending by name in UTF-8 byte order.
    pub fn sort(&mut self) {
        self.skills
            .sort_by(|a, b| a.name.as_bytes().cmp(b.name.as_bytes()));
    }
}

// --------------------------- reading (serde) ---------------------------

#[derive(Debug, Deserialize)]
struct RawLock {
    version: Option<i64>,
    generated_by: Option<String>,
    #[serde(default)]
    skills: Vec<RawLockSkill>,
}

#[derive(Debug, Deserialize)]
struct RawLockSkill {
    name: String,
    content_sha256: String,
    source: RawLockSource,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
enum RawLockSource {
    Git {
        repo: String,
        #[serde(rename = "ref")]
        ref_: Option<String>,
        subdir: Option<String>,
        resolved_ref: Option<String>,
        resolved_commit: String,
    },
    Tar {
        url: String,
        subdir: Option<String>,
        archive_sha256: String,
    },
    Zip {
        url: String,
        subdir: Option<String>,
        archive_sha256: String,
    },
    Local {
        path: String,
    },
}

/// Parse lockfile text. Returns `Ok(None)` only via [`load`] for a missing
/// file; here a present-but-unparseable file errors.
pub fn parse(text: &str) -> Result<Lockfile> {
    let raw: RawLock = toml::from_str(text)
        .map_err(|e| SkmError::general(format!("cannot parse skm.lock: {e}")))?;
    let version = match raw.version {
        None => {
            return Err(SkmError::general(
                "error: skm.lock is missing required 'version' field; re-run 'skm lock' to regenerate",
            ));
        }
        Some(v) => v,
    };
    if version != LOCK_VERSION {
        return Err(SkmError::general(format!(
            "unsupported lock version {version}; re-run 'skm lock' to regenerate"
        )));
    }
    // Normalize git/zip/tar lock subdirs the same way the manifest is normalized
    // — keeps old locks containing `./docx` from triggering spurious
    // re-resolves after the manifest started normalizing.
    let norm_subdir = |s: Option<String>| -> Result<Option<String>> {
        match s {
            Some(s) => Ok(Some(source::validate_source_subdir(&s)?)),
            None => Ok(None),
        }
    };
    let mut skills = Vec::with_capacity(raw.skills.len());
    for s in raw.skills {
        let source = match s.source {
            RawLockSource::Git {
                repo,
                ref_,
                subdir,
                resolved_ref,
                resolved_commit,
            } => {
                // Guard against corrupt/hand-edited lockfiles: a non-hex
                // resolved_commit could cause short_hex to behave
                // unexpectedly (it is always rendered in summaries).
                if !resolved_commit.is_empty()
                    && !resolved_commit.chars().all(|c| c.is_ascii_hexdigit())
                {
                    return Err(SkmError::general(format!(
                        "invalid resolved_commit in lock: '{resolved_commit}' is not hex"
                    )));
                }
                LockSource::Git {
                    repo,
                    ref_,
                    subdir: norm_subdir(subdir)?,
                    resolved_ref,
                    resolved_commit,
                }
            }
            RawLockSource::Tar {
                url,
                subdir,
                archive_sha256,
            } => LockSource::Tar {
                url,
                subdir: norm_subdir(subdir)?,
                archive_sha256: Sha256::from_hex(&archive_sha256)?,
            },
            RawLockSource::Zip {
                url,
                subdir,
                archive_sha256,
            } => LockSource::Zip {
                url,
                subdir: norm_subdir(subdir)?,
                archive_sha256: Sha256::from_hex(&archive_sha256)?,
            },
            RawLockSource::Local { path } => LockSource::Local { path },
        };
        skills.push(LockSkill {
            name: s.name,
            content_sha256: Sha256::from_hex(&s.content_sha256)?,
            source,
        });
    }
    Ok(Lockfile {
        version,
        generated_by: raw.generated_by.unwrap_or_default(),
        skills,
    })
}

/// Load a lockfile, returning `Ok(None)` if the file does not exist.
pub fn load(path: &Path) -> Result<Option<Lockfile>> {
    match std::fs::read_to_string(path) {
        Ok(text) => Ok(Some(parse(&text)?)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(SkmError::io(format!(
            "cannot read '{}': {e}",
            path.display()
        ))),
    }
}

// --------------------------- writing (toml_edit) ---------------------------

/// Serialize the lockfile to deterministic TOML text (field order).
pub fn serialize(lock: &Lockfile) -> String {
    let mut doc = DocumentMut::new();
    doc.insert("version", toml_edit::value(lock.version));
    doc.insert("generated_by", toml_edit::value(lock.generated_by.clone()));

    // Sort skills by name without cloning the whole lockfile.
    let mut indices: Vec<usize> = (0..lock.skills.len()).collect();
    indices.sort_by(|&a, &b| {
        lock.skills[a]
            .name
            .as_bytes()
            .cmp(lock.skills[b].name.as_bytes())
    });

    let mut aot = ArrayOfTables::new();
    for &i in &indices {
        let skill = &lock.skills[i];
        let mut t = Table::new();
        t.insert("name", toml_edit::value(skill.name.clone()));
        t.insert(
            "content_sha256",
            toml_edit::value(skill.content_sha256.to_hex()),
        );

        let mut src = Table::new();
        match &skill.source {
            LockSource::Git {
                repo,
                ref_,
                subdir,
                resolved_ref,
                resolved_commit,
            } => {
                src.insert("type", toml_edit::value("git"));
                src.insert("repo", toml_edit::value(repo.clone()));
                if let Some(r) = ref_ {
                    src.insert("ref", toml_edit::value(r.clone()));
                }
                if let Some(sd) = subdir {
                    src.insert("subdir", toml_edit::value(sd.clone()));
                }
                if let Some(rr) = resolved_ref {
                    src.insert("resolved_ref", toml_edit::value(rr.clone()));
                }
                src.insert("resolved_commit", toml_edit::value(resolved_commit.clone()));
            }
            LockSource::Tar {
                url,
                subdir,
                archive_sha256,
            } => {
                src.insert("type", toml_edit::value("tar"));
                src.insert("url", toml_edit::value(url.clone()));
                if let Some(p) = subdir {
                    src.insert("subdir", toml_edit::value(p.clone()));
                }
                src.insert("archive_sha256", toml_edit::value(archive_sha256.to_hex()));
            }
            LockSource::Zip {
                url,
                subdir,
                archive_sha256,
            } => {
                src.insert("type", toml_edit::value("zip"));
                src.insert("url", toml_edit::value(url.clone()));
                if let Some(p) = subdir {
                    src.insert("subdir", toml_edit::value(p.clone()));
                }
                src.insert("archive_sha256", toml_edit::value(archive_sha256.to_hex()));
            }
            LockSource::Local { path } => {
                src.insert("type", toml_edit::value("local"));
                src.insert("path", toml_edit::value(path.clone()));
            }
        }
        t.insert("source", Item::Table(src));
        aot.push(t);
    }
    doc.insert("skills", Item::ArrayOfTables(aot));
    doc.to_string()
}

/// Atomically write the lockfile (.tmp → rename).
pub fn write(path: &Path, lock: &Lockfile) -> Result<()> {
    atomic_write(path, &serialize(lock))
}

/// Compare two lockfiles for substantive equality, ignoring `generated_by`
/// (write timing). Uses structural comparison (no serialization) to avoid
/// allocation in the hot lock-write-or-skip path.
pub fn content_eq(a: &Lockfile, b: &Lockfile) -> bool {
    if a.version != b.version || a.skills.len() != b.skills.len() {
        return false;
    }
    let mut a_skills: Vec<&LockSkill> = a.skills.iter().collect();
    let mut b_skills: Vec<&LockSkill> = b.skills.iter().collect();
    a_skills.sort_by(|x, y| x.name.as_bytes().cmp(y.name.as_bytes()));
    b_skills.sort_by(|x, y| x.name.as_bytes().cmp(y.name.as_bytes()));
    a_skills == b_skills
}

/// Atomic file write helper (also used by the manifest writer).
pub fn atomic_write(path: &Path, contents: &str) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| SkmError::io("invalid path: no parent"))?;
    std::fs::create_dir_all(parent)
        .map_err(|e| SkmError::io(format!("cannot create '{}': {e}", parent.display())))?;
    let tmp = parent.join(format!(".{}.tmp.{}", file_name(path), fsutil::rand_token()));
    std::fs::write(&tmp, contents)
        .map_err(|e| SkmError::io(format!("cannot write temp file: {e}")))?;
    std::fs::rename(&tmp, path)
        .map_err(|e| SkmError::io(format!("cannot rename into place: {e}")))?;
    Ok(())
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "file".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_version_errors_distinctly() {
        // The lock's missing version mirrors the manifest's wording rather
        // than reporting a fake "unsupported lock version 0".
        let err = parse("generated_by = \"skm 0.0\"\n").unwrap_err();
        let msg = err.message;
        assert!(
            msg.contains("missing required 'version' field"),
            "expected missing-version wording, got: {msg}"
        );
        assert!(
            !msg.contains("version 0"),
            "should not mention version 0: {msg}"
        );
    }

    #[test]
    fn compat_note_follows_semver_rule() {
        // Identical → no note.
        assert_eq!(compat_note("skm 0.1.0", "skm 0.1.0"), None);
        // Empty (no generated_by recorded) → no note.
        assert_eq!(compat_note("", "skm 0.1.0"), None);

        // 0.x: ANY difference warns (semver 0.x can break at any bump).
        assert!(compat_note("skm 0.1.0", "skm 0.2.0").is_some());
        assert!(compat_note("skm 0.1.0", "skm 0.1.1").is_some());

        // >=1.0: minor/patch differences are compatible → NO note.
        assert_eq!(compat_note("skm 1.2.0", "skm 1.3.0"), None);
        assert_eq!(compat_note("skm 1.2.0", "skm 1.2.9"), None);
        // >=1.0: a major difference warns.
        assert!(
            compat_note("skm 1.9.0", "skm 2.0.0")
                .unwrap()
                .contains("major version differs")
        );

        // Pre-release / build metadata do NOT participate: same core → no note.
        assert_eq!(compat_note("skm 1.2.0-rc.1", "skm 1.2.0"), None);
        assert_eq!(compat_note("skm 1.2.0+abc", "skm 1.2.0+def"), None);

        // Unparseable → conservative raw-inequality note.
        assert!(compat_note("skm dev", "skm 1.2.0").is_some());
    }

    #[test]
    fn roundtrip_stable() {
        let lock = Lockfile {
            version: 1,
            generated_by: "skm 0.1.0".to_string(),
            skills: vec![
                LockSkill {
                    name: "zeta".to_string(),
                    content_sha256: Sha256::from_hex("ffff").unwrap(),
                    source: LockSource::Local {
                        path: "./vendor/z".to_string(),
                    },
                },
                LockSkill {
                    name: "alpha".to_string(),
                    content_sha256: Sha256::from_hex("aaaa").unwrap(),
                    source: LockSource::Git {
                        repo: "https://example.com/r".to_string(),
                        ref_: Some("main".to_string()),
                        subdir: Some("docx".to_string()),
                        resolved_ref: Some("main".to_string()),
                        resolved_commit: "9f3c".to_string(),
                    },
                },
            ],
        };
        let text = serialize(&lock);
        // Sorted: alpha before zeta.
        assert!(text.find("alpha").unwrap() < text.find("zeta").unwrap());
        let parsed = parse(&text).unwrap();
        assert_eq!(parsed.skills.len(), 2);
        let text2 = serialize(&parsed);
        assert_eq!(text, text2);
    }

    // -- short_hex safety --

    #[test]
    fn short_hex_truncates_to_12() {
        let sha = "a".repeat(40);
        assert_eq!(short_hex(&sha), &sha[..12]);
    }

    #[test]
    fn short_hex_short_input_returns_whole() {
        assert_eq!(short_hex("9f3c"), "9f3c");
    }

    #[test]
    fn short_hex_multibyte_boundary_does_not_panic() {
        // 11 ASCII chars + 'é' (2 bytes) at position 11–12.
        // The 12-byte mark falls inside the 'é' → must back up to byte 11.
        let input = "aaaaaaaaaaébbbb";
        // input: bytes 0-10 = 'a', bytes 11-12 = 'é', bytes 13-16 = 'b'
        // char boundary at byte 11 (before 'é'), but byte 12 is mid-character.
        let result = short_hex(input);
        // Must not panic; must return a valid &str prefix.
        assert!(input.starts_with(result));
        assert!(result.len() <= 12);
    }

    // -- parse validation: resolved_commit must be hex --

    #[test]
    fn parse_rejects_nonhex_resolved_commit() {
        let lock = Lockfile {
            version: 1,
            generated_by: "skm 0.1.0".to_string(),
            skills: vec![LockSkill {
                name: "x".to_string(),
                content_sha256: Sha256::from_hex("aaaa").unwrap(),
                source: LockSource::Git {
                    repo: "https://example.com/r".to_string(),
                    ref_: None,
                    subdir: None,
                    resolved_ref: None,
                    resolved_commit: "NOT-A-COMMIT".to_string(),
                },
            }],
        };
        let text = serialize(&lock);
        let err = parse(&text).unwrap_err();
        assert!(
            err.message.contains("resolved_commit"),
            "expected resolved_commit error, got: {}",
            err.message
        );
        assert!(
            err.message.contains("NOT-A-COMMIT"),
            "error should name the bad value"
        );
    }
}
